### ISSUE TITLE
SSL libs may not be compiled in

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent-omnibus#4]
In attempting to run the omnibus agent in an extremely limited environment, I attempted to run dogstatsd standalone mode, however when running, I receive the following error:

```shellsession
$ API_KEY=111 ./run-dogstatsd.sh
Traceback (most recent call last):
  File ".apt/opt/datadog-agent/agent/dogstatsd.py", line 446, in <module>
    sys.exit(main())
  File ".apt/opt/datadog-agent/agent/dogstatsd.py", line 415, in main
    reporter, server, cnf = init(config_path, use_watchdog=True, use_forwarder=opts.use_forwarder, args=args)
  File ".apt/opt/datadog-agent/agent/dogstatsd.py", line 395, in init
    reporter = Reporter(interval, aggregator, target, api_key, use_watchdog, event_chunk_size)
  File ".apt/opt/datadog-agent/agent/dogstatsd.py", line 90, in __init__
    self.http_conn_cls = http_client.HTTPSConnection
AttributeError: 'module' object has no attribute 'HTTPSConnection'
```

Sure enough, the module does not have the attribute:
```shellsession
$ .apt/opt/datadog-agent/embedded/bin/python  -c "import sys; print sys.version_info"
sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)
$ .apt/opt/datadog-agent/embedded/bin/python  -c "import httplib; print filter(lambda attr: attr.startswith('HTTP'), dir(httplib))"
['HTTP', 'HTTPConnection', 'HTTPException', 'HTTPMessage', 'HTTPResponse', 'HTTPS_PORT', 'HTTP_PORT', 'HTTP_VERSION_NOT_SUPPORTED']
```

I then tried using the `requests` library, as that's the one we use in the forwarder, considering maybe we rewrite the dogstatsd standalone emitter to be the same as the forwarder, and didn't get much better results:

```python
>>> import requests
>>> url = 'http://www.google.com/'
>>> r = requests.get(url)
>>> r.text
u'<!doctype html><html itemscope=""...........


>>> url = 'https://app.datadoghq.com'
>>> r = requests.get(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 304, in _make_request
    self._validate_conn(conn)
  File "/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 722, in _validate_conn
    conn.connect()
  File "/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 169, in connect
    self.sock = ssl.wrap_socket(conn, self.key_file, self.cert_file)
AttributeError: 'NoneType' object has no attribute 'wrap_socket'


>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/.apt/opt/datadog-agent/embedded/lib/python2.7/ssl.py", line 60, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /app/.apt/opt/datadog-agent/embedded/lib/python2.7/lib-dynload/_ssl.so: undefined symbol: SSLv2_method
```

This is datadog-agent 5.1.0, pyopenssl 0.14

This may be due to the correct ssl libs not being present during compile phase, which then leads to the HTTPS* attributes not being available.

An obscure thread on the topic mentions adding the C dev modules before compiling: https://github.com/pypa/pip/issues/833#issuecomment-14898894

I'm not entirely certain where we would place the `apt-get install libssl-dev` in the pipeline, as well as see why we're not getting Python 2.7.8 either.

package: http://packages.ubuntu.com/trusty/libssl-dev

A well-formed, ssl-compiled httplib output will look like this:
```shellsession
$ python -c "import httplib; print filter(lambda attr: attr.startswith('HTTP'), dir(httplib))"
['HTTP', 'HTTPConnection', 'HTTPException', 'HTTPMessage', 'HTTPResponse', 'HTTPS', 'HTTPSConnection', 'HTTPS_PORT', 'HTTP_PORT', 'HTTP_VERSION_NOT_SUPPORTED']
```

**Comment by olivielpeau** [comment]
Closing the issue as the workaround seems to be good enough.
